"""Add Theme model

Revision ID: d720b65bf72b
Revises: f76697b37e3d
Create Date: 2025-02-08 19:40:44.783673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd720b65bf72b'
down_revision = 'f76697b37e3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('themes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('themes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('course_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name='fk_themes_course_id_courses'),
    sa.PrimaryKeyConstraint('id', name='pk_themes')
    )
    # ### end Alembic commands ###
